### ISSUE TITLE
start_hotfix_container does not start the patched image

### ISSUE THREAD

**Issue by glennvdw** [andreaskaris/openstack_containerized_hotfix#7]
In the mentioned script you run:

> sed -i "s#\"${ORIGINAL_IMAGE}\"#\"${HOTFIX_IMAGE}\"#" /tmp/docker-container-startup-config-step_4.${HOTFIX_TAG}.json

This replaces the first match only. I believe this should become:

> sed -i "s#\"${ORIGINAL_IMAGE}\"#\"${HOTFIX_IMAGE}\"#g" /tmp/docker-container-startup-config-step_4.${HOTFIX_TAG}.json

**Comment by cgoncalves** [comment]
Seems to have been fixed in https://github.com/andreaskaris/openstack_containerized_hotfix/commit/107aa5d951e0a12d538927a5fe05d869f7c1b999

**Comment by andreaskaris** [comment]
Yes, thanks!
